### ISSUE TITLE
Rivet 0.90 and 0.91 fork don't start on Debian/QubesOS

### ISSUE THREAD

**Issue by kord1e** [IanWraith/Rivet#4]
Reporting this mainly for the @priyom team that has forked the project.

Rivet doesn't start on Debian (running under QubesOS), tried both forked 0.91 and original 0.90. The following messages appear. I think this might be related to the new Pipewire audio system but not sure about this.

```
$ java -jar rivet-0.91.jar 
Exception in thread "main" java.lang.IllegalArgumentException: Mixer not supported: null
	at java.desktop/javax.sound.sampled.AudioSystem.getMixer(AudioSystem.java:210)
	at org.e2k.AudioMixer.setDefaultLine(AudioMixer.java:88)
	at org.e2k.AudioMixer.<init>(AudioMixer.java:43)
	at org.e2k.InputThread.<init>(InputThread.java:48)
	at org.e2k.Rivet.<init>(Rivet.java:74)
	at org.e2k.Rivet.main(Rivet.java:120)
```

Java version information:

```
$ java -version
openjdk version "17.0.12" 2024-07-16
OpenJDK Runtime Environment (build 17.0.12+7-Debian-2deb12u1)
OpenJDK 64-Bit Server VM (build 17.0.12+7-Debian-2deb12u1, mixed mode, sharing)
```

SDRtrunk has had similar issue, see:
https://github.com/DSheirer/sdrtrunk/issues/335

**Comment by kord1e** [comment]
And it works on Fedora, also running under QubesOS and Java 17.
